[project]
name = "pprint-stat"
version = "0.1.0"
description = "Command line tool to pretty print the /proc/[pid]/stat file, mapping values to fields"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pprint-stat = "pprint_stat.cli:app"